Homework 1
ekrivchenko/practice pull request #2
Opened 2017-08-04 06:01 UTC by ekrivchenko

Add new functionality for changing user values

2017-08-05 19:01 UTC, istepanko requested changes

2017-08-05 19:01 UTC, istepanko commented on project1/UserOperations.py
> +                print("\nLast name for that user is changed successfully")
`print("\nLast name for that user is changed successfully")`
What if file write fails???

2017-08-05 19:01 UTC, istepanko commented on project1/UserOperations.py
> +                print("\nEmail for that user is changed successfully")
Same

2017-08-05 19:01 UTC, istepanko commented on project1/UserClass.py
> +
Why renaming????

2017-08-05 19:37 UTC, ekrivchenko commented on project1/UserClass.py
> +
renaming what?

2017-08-10 00:18 UTC, istepanko approved these changes

2017-08-10 00:18 UTC, merged